# Aviation Accidents Analysis

You are part of a consulting firm that is tasked to do an analysis of commercial and passenger jet airline safety. The client (an airline/airplane insurer) is interested in knowing what types of aircraft (makes/models) exhibit low rates of total destruction and low likelihood of fatal or serious passenger injuries in the event of an accident. They are also interested in any general variables/conditions that might be at play. Your analysis will be based off of aviation accident data accumulated from the years 1948-2023. 

Our client is only interested in airplane makes/models that are professional builds and could potentially still be active. Assume a max lifetime of 40 years for a make/model retirement and make sure to filter your data accordingly (i.e. from 1983 onwards). They would also like separate recommendations for small aircraft vs. larger passenger models. **In addition, make sure that claims that you make are statistically robust and that you have enough samples when making comparisons between groups.**


In this summative assessment you will demonstrate your ability to:
- **Use Pandas to load, inspect, and clean the dataset appropriately.**
- **Transform relevant columns to create measures that address the problem at hand.**
- conduct EDA: visualization and statistical measures to systematically understand the structure of the data
- recommend a set of airplanes and makes conforming to the client's request and identify at least *two* factors contributing to airplane safety. You must provide supporting evidence (visuals, summary statistics, tables) for each claim you make.

### Make relevant library imports

In [122]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Data Loading and Inspection

### Load in data from the relevant directory and inspect the dataframe.
- inspect NaNs, datatypes, and summary statistics

In [123]:
df =  pd.read_csv('AviationData.csv', encoding='ISO-8859-1', low_memory=False)
df

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88884,20221227106491,Accident,ERA23LA093,2022-12-26,"Annapolis, MD",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,0.0,NaN,NaN,NaN,29-12-2022
88885,20221227106494,Accident,ERA23LA095,2022-12-26,"Hampton, NH",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88886,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022
88887,20221227106498,Accident,WPR23LA076,2022-12-26,"Morgan, UT",United States,NaN,NaN,NaN,NaN,...,Personal,MC CESSNA 210N LLC,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88888,20221230106513,Accident,ERA23LA097,2022-12-29,"Athens, GA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,1.0,NaN,NaN,NaN,30-12-2022

In [124]:
df.shape

(88889, 31)

In [125]:
df.info

<bound method DataFrame.info of              Event.Id Investigation.Type Accident.Number  Event.Date  \
0      20001218X45444           Accident      SEA87LA080  1948-10-24
1      20001218X45447           Accident      LAX94LA336  1962-07-19
2      20061025X01555           Accident      NYC07LA005  1974-08-30
3      20001218X45448           Accident      LAX96LA321  1977-06-19
4      20041105X01764           Accident      CHI79FA064  1979-08-02
...               ...                ...             ...         ...
88884  20221227106491           Accident      ERA23LA093  2022-12-26
88885  20221227106494           Accident      ERA23LA095  2022-12-26
88886  20221227106497           Accident      WPR23LA075  2022-12-26
88887  20221227106498           Accident      WPR23LA076  2022-12-26
88888  20221230106513           Accident      ERA23LA097  2022-12-29

              Location        Country   Latitude   Longitude Airport.Code  \
0      MOOSE CREEK, ID  United States        NaN         NaN          NaN
1       BRIDGEPORT, CA  United States        NaN         NaN          NaN
2        Saltville, VA  United States  36.922223  -81.878056          NaN
3           EUREKA, CA  United States        NaN         NaN          NaN
4           Canton, OH  United States        NaN         NaN          NaN
...                ...            ...        ...         ...          ...
88884    Annapolis, MD  United States        NaN         NaN          NaN
88885      Hampton, NH  United States        NaN         NaN          NaN
88886       Payson, AZ  United States    341525N    1112021W          PAN
88887       Morgan, UT  United States        NaN         NaN          NaN
88888       Athens, GA  United States        NaN         NaN          NaN

      Airport.Name  ... Purpose.of.flight         Air.carrier  \
0              NaN  ...          Personal                 NaN
1              NaN  ...          Personal                 NaN
2              NaN  ...          Personal                 NaN
3              NaN  ...          Personal                 NaN
4              NaN  ...          Personal                 NaN
...            ...  ...               ...                 ...
88884          NaN  ...          Personal                 NaN
88885          NaN  ...               NaN                 NaN
88886       PAYSON  ...          Personal                 NaN
88887          NaN  ...          Personal  MC CESSNA 210N LLC
88888          NaN  ...          Personal                 NaN

      Total.Fatal.Injuries Total.Serious.Injuries Total.Minor.Injuries  \
0                      2.0                    0.0                  0.0
1                      4.0                    0.0                  0.0
2                      3.0                    NaN                  NaN
3                      2.0                    0.0                  0.0
4                      1.0                    2.0                  NaN
...                    ...                    ...                  ...
88884                  0.0                    1.0                  0.0
88885                  0.0                    0.0                  0.0
88886                  0.0                    0.0                  0.0
88887                  0.0                    0.0                  0.0
88888                  0.0                    1.0                  0.0

      Total.Uninjured Weather.Condition  Broad.phase.of.flight  \
0                 0.0               UNK                 Cruise
1                 0.0               UNK                Unknown
2                 NaN               IMC                 Cruise
3                 0.0               IMC                 Cruise
4                 0.0               VMC               Approach
...               ...               ...                    ...
88884             0.0               NaN                    NaN
88885             0.0               NaN                    NaN
88886             1.0               VMC                    NaN
88887             0.0               NaN                    NaN
88888             1.0               NaN                    NaN

        Report.Status Publication.Date
0      Probable Cause              NaN
1      Probable Cause       19-09-1996
2      Probable Cause       26-02-2007
3      Probable Cause       12-09-2000
4      Probable Cause       16-04-1980
...               ...              ...
88884             NaN       29-12-2022
88885             NaN              NaN
88886             NaN       27-12-2022
88887             NaN              NaN
88888             NaN       30-12-2022

[88889 rows x 31 columns]>

In [126]:
df.isna().sum()
df

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88884,20221227106491,Accident,ERA23LA093,2022-12-26,"Annapolis, MD",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,0.0,NaN,NaN,NaN,29-12-2022
88885,20221227106494,Accident,ERA23LA095,2022-12-26,"Hampton, NH",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88886,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022
88887,20221227106498,Accident,WPR23LA076,2022-12-26,"Morgan, UT",United States,NaN,NaN,NaN,NaN,...,Personal,MC CESSNA 210N LLC,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
88888,20221230106513,Accident,ERA23LA097,2022-12-29,"Athens, GA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,1.0,NaN,NaN,NaN,30-12-2022

In [127]:
df['Amateur.Built'].value_counts(dropna=False)

Amateur.Built
No     80312
Yes     8475
NaN      102
Name: count, dtype: int64

In [128]:
# Keep only professional builds
df = df[df['Amateur.Built'] == 'No']

In [129]:
# Verify that only 'No' remains and check remaining records
print(df['Amateur.Built'].value_counts())
print(f"Remaining records: {df.shape[0]}")

Amateur.Built
No    80312
Name: count, dtype: int64
Remaining records: 80312

## Data Cleaning

### Filtering aircrafts and events

We want to filter the dataset to include aircraft that the client is interested in an analysis of:
- inspect relevant columns
- figure out any reasonable imputations
- filter the dataset

In [130]:
df['Event.Date'] = pd.to_datetime(df['Event.Date'])

In [131]:
df = df[df['Event.Date'].dt.year >= 1983]

In [132]:
# df = df[['Aircraft.Category'] == 'Airplane']

In [133]:
df['Aircraft.Category'].value_counts(dropna=False)

Aircraft.Category
NaN                  51555
Airplane             21447
Helicopter            3022
Glider                 434
Balloon                199
Weight-Shift           139
Powered Parachute       83
Gyrocraft               31
Ultralight              18
Unknown                 11
WSFT                     9
Powered-Lift             5
Blimp                    4
UNK                      2
Rocket                   1
Name: count, dtype: int64

In [134]:
print(df[df['Aircraft.Category'].isna()]['Make'].value_counts().head(10))

Make
Cessna      18539
Piper       10074
Beech        3639
Bell         1779
Boeing       1270
Grumman       917
Mooney        904
Bellanca      758
Hughes        685
Robinson      658
Name: count, dtype: int64

In [135]:
# Fill missing Aircraft.Category entries with 'Airplane'
df['Aircraft.Category'] = df['Aircraft.Category'].fillna('Airplane')

In [136]:
# Filter to keep only Airplanes (removing Helicopters, Gliders, Balloons, etc.)
df = df[df['Aircraft.Category'] == 'Airplane']

### Cleaning and constructing Key Measurables

Injuries and robustness to destruction are a key interest point for the client. Clean and impute relevant columns and then create derived fields that best quantifies what the client wishes to track. **Use commenting or markdown to explain any cleaning assumptions as well as any derived columns you create.**

**Construct metric for fatal/serious injuries**

*Hint:* Estimate the total number of passengers on each flight. The likelihood of serious / fatal injury can be estimated as a fraction from this.

In [137]:
# Injury-related columns
injury_cols = [
    'Total.Fatal.Injuries',
    'Total.Serious.Injuries',
    'Total.Minor.Injuries',
    'Total.Uninjured'
]

# Fill NaN values with 0 across these columns
df[injury_cols] = df[injury_cols].fillna(0)

In [138]:
print(df[injury_cols].isna().sum())

Total.Fatal.Injuries      0
Total.Serious.Injuries    0
Total.Minor.Injuries      0
Total.Uninjured           0
dtype: int64

In [139]:
# Sum across the 4 columns for each row to get total occupants on board
df['Total_on_board'] = df[injury_cols].sum(axis=1)

In [140]:

# Compute severe injury fraction guarded against division by zero
df['Severe_Injury_Fraction'] = np.where(
    df['Total_on_board'] > 0,
    (df['Total.Fatal.Injuries'] + df['Total.Serious.Injuries']) / df['Total_on_board'],
    np.nan
)

In [141]:
# Inspect summary statistics and check that values range between 0 and 1
print(df[['Total_on_board', 'Severe_Injury_Fraction']].describe())

       Total_on_board  Severe_Injury_Fraction
count    73002.000000            71824.000000
mean         6.914400                0.271188
std         30.321715                0.427856
min          0.000000                0.000000
25%          1.000000                0.000000
50%          2.000000                0.000000
75%          3.000000                0.666667
max        699.000000                1.000000

**Aircraft.Damage**
- identify and execute any cleaning tasks
- construct a derived column tracking whether an aircraft was destroyed or not.

In [142]:
# Create a derived binary column (1 if Destroyed, 0 otherwise)
df['is_destroyed'] = (df['Aircraft.damage'] == 'Destroyed').astype(int)

In [143]:
# Check counts of 1s (destroyed) vs 0s (not destroyed)
print(df['is_destroyed'].value_counts())

is_destroyed
0    58044
1    14958
Name: count, dtype: int64

### Investigate the *Make* column
- Identify cleaning tasks here
- List cleaning tasks clearly in markdown
- Execute the cleaning tasks
- For your analysis, keep Makes with a reasonable number (you can put the threshold at 50 though lower could work as well)

In [144]:
df['Make'] = df['Make'].astype(str).str.strip().str.upper()

In [145]:
# Define dictionary mapping synonyms and variants to standard names
make_mapping = {
    'MCDONNELL-DOUGLAS': 'MCDONNELL DOUGLAS',
    'MCDONNELL DOUGLAS AIRCRAFT CO': 'MCDONNELL DOUGLAS',
    'MCDONNELL DOUGLAS CORPORATION': 'MCDONNELL DOUGLAS',
    'THE BOEING COMPANY': 'BOEING',
    'BOEING COMPANY': 'BOEING',
    'AIRBUS INDUSTRIE': 'AIRBUS',
    'AIRBUS INDUSTRIES': 'AIRBUS',
    'DEHAVILLAND': 'DE HAVILLAND',
    'BEECHCRAFT': 'BEECH',
    'BEECH AIRCRAFT': 'BEECH',
    'BEECH AIRCRAFT CORPORATION': 'BEECH',
    'CESSNA AIRCRAFT CO': 'CESSNA',
    'CESSNA AIRCRAFT COMPANY': 'CESSNA',
    'PIPER AIRCRAFT': 'PIPER',
    'PIPER AIRCRAFT INC': 'PIPER',
    'PIPER AIRCRAFT CORPORATION': 'PIPER'
}

# Apply the mapping
df['Make'] = df['Make'].replace(make_mapping)

In [146]:
# Count occurrences of each cleaned make
counts = df['Make'].value_counts()

In [147]:
# Get the list of makes with at least 50 occurrences
valid_makes = counts[counts >= 50].index

In [148]:
# Filter DataFrame to keep only valid makes
df = df[df['Make'].isin(valid_makes)]

In [149]:
# Verify top makes and remaining dataset shape
print(df['Make'].value_counts().head(15))
print(f"Remaining rows after make filtering: {len(df)}")

Make
CESSNA               25775
PIPER                14144
BEECH                 5126
BOEING                2664
BELL                  1793
MOONEY                1271
GRUMMAN               1064
BELLANCA               978
HUGHES                 686
ROBINSON               676
AIR TRACTOR            673
AERONCA                607
MCDONNELL DOUGLAS      584
MAULE                  571
SCHWEIZER              549
Name: count, dtype: int64
Remaining rows after make filtering: 67696

### Inspect Model column
- Get rid of any NaNs.
- Inspect the column and counts for each model/make. Are model labels unique to each make?
- If not, create a derived column that is a unique identifier for a given plane type.

In [150]:
# Drop rows where df\['Model'\].isna()
df['Model'].isna()

3601     False
3602     False
3603     False
3604     False
3605     False
         ...
88884    False
88885    False
88886    False
88887    False
88888    False
Name: Model, Length: 67696, dtype: bool

In [151]:
# Clean text
df['Model'].astype(str).str.strip().str.upper()

3601           182P
3602          182RG
3603           182P
3604     PA-28R-200
3605            140
            ...
88884     PA-28-151
88885          7ECA
88886         8GCBC
88887          210N
88888     PA-24-260
Name: Model, Length: 67696, dtype: str

In [152]:
# Create compound identifier
df['Make_Model'] = df['Make'] + '_' + df['Model']

In [153]:
# Inspect the new column alongside Make and Model
print(df[['Make', 'Model', 'Make_Model']].head(10))

# Check top models by frequency
print("\nTop aircraft types:")
print(df['Make_Model'].value_counts().head(10))

                Make       Model                Make_Model
3601          CESSNA        182P               CESSNA_182P
3602          CESSNA       182RG              CESSNA_182RG
3603          CESSNA        182P               CESSNA_182P
3604           PIPER  PA-28R-200          PIPER_PA-28R-200
3605          CESSNA         140                CESSNA_140
3606   BALLOON WORKS  FIREFLY 7B  BALLOON WORKS_FIREFLY 7B
3607          CESSNA        340A               CESSNA_340A
3608  NORTH AMERICAN        T-6G       NORTH AMERICAN_T-6G
3609           PIPER   PA-24-250           PIPER_PA-24-250
3610           PIPER  PA-32-301R          PIPER_PA-32-301R

Top aircraft types:
Make_Model
CESSNA_152         2230
CESSNA_172         1649
CESSNA_172N        1093
PIPER_PA-28-140     863
CESSNA_172M         759
CESSNA_150          752
CESSNA_172P         665
CESSNA_182          617
CESSNA_180          595
CESSNA_150M         551
Name: count, dtype: int64

### Cleaning other columns
- there are other columns containing data that might be related to the outcome of an accident. We list a few here:
- Engine.Type
- Weather.Condition
- Number.of.Engines
- Purpose.of.flight
- Broad.phase.of.flight

Inspect and identify potential cleaning tasks in each of the above columns. Execute those cleaning tasks. 

**Note**: You do not necessarily need to impute or drop NaNs here.

In [154]:
# Load state codes
states = pd.read_csv('USState_Codes.csv')

In [155]:
# Extract postal abbreviation
df['State_Code'] = df['Location'].str.split(',').str[-1].str.strip()

In [156]:
# Merge on abbreviation to obtain full state names
df.merge(states, left_on='State_Code', right_on='Abbreviation', how='left')

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Broad.phase.of.flight,Report.Status,Publication.Date,Total_on_board,Severe_Injury_Fraction,is_destroyed,Make_Model,State_Code,US_State,Abbreviation
0,20001214X42095,Accident,SEA83LA036,1983-01-01,"NEWPORT, OR",United States,NaN,NaN,ONP,NEWPORT MUNICIPAL,...,Approach,Probable Cause,NaN,4.0,0.0,0,CESSNA_182P,OR,Oregon,OR
1,20001214X42067,Accident,MKC83LA056,1983-01-01,"WOODBINE, IA",United States,NaN,NaN,3YR,MUNICIPAL,...,Landing,Probable Cause,NaN,2.0,0.0,0,CESSNA_182RG,IA,Iowa,IA
2,20001214X42063,Accident,MKC83LA050,1983-01-01,"MARYVILLE, MO",United States,NaN,NaN,78Y,RANKIN,...,Takeoff,Probable Cause,NaN,1.0,0.0,0,CESSNA_182P,MO,Missouri,MO
3,20001214X42018,Accident,LAX83FUG11,1983-01-01,"UPLAND, CA",United States,NaN,NaN,CCB,CABLE,...,Approach,Probable Cause,NaN,2.0,0.0,0,PIPER_PA-28R-200,CA,California,CA
4,20001214X41951,Accident,CHI83LA074,1983-01-01,"SPRINGBROOK, WI",United States,NaN,NaN,NaN,SPRINGBROOK,...,Landing,Probable Cause,NaN,2.0,0.0,0,CESSNA_140,WI,Wisconsin,WI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67691,20221227106491,Accident,ERA23LA093,2022-12-26,"Annapolis, MD",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,29-12-2022,1.0,1.0,0,PIPER_PA-28-151,MD,Maryland,MD
67692,20221227106494,Accident,ERA23LA095,2022-12-26,"Hampton, NH",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,0,BELLANCA_7ECA,NH,New Hampshire,NH
67693,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,NaN,NaN,27-12-2022,1.0,0.0,0,AMERICAN CHAMPION AIRCRAFT_8GCBC,AZ,Arizona,AZ
67694,20221227106498,Accident,WPR23LA076,2022-12-26,"Morgan, UT",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,0,CESSNA_210N,UT,Utah,UT
67695,20221230106513,Accident,ERA23LA097,2022-12-29,"Athens, GA",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,30-12-2022,2.0,0.5,0,PIPER_PA-24-260,GA,Georgia,GA

In [157]:
# Weather.Condition: Standardize casing and group placeholders
df['Weather.Condition'] = df['Weather.Condition'].astype(str).str.strip().str.upper()
df['Weather.Condition'] = df['Weather.Condition'].replace({
    'UNK': 'UNKNOWN',
    'NAN': np.nan
})

# Engine.Type: Standardize casing and collapse unknown variants
df['Engine.Type'] = df['Engine.Type'].astype(str).str.strip().str.title()
df['Engine.Type'] = df['Engine.Type'].replace({
    'Unk': 'Unknown',
    'None': 'Unknown',
    'Lr': 'Unknown',
    'Nan': np.nan
})

# Number.of.Engines-- Replace invalid engine count (0 engines) with NaN
# Airplanes must have at least 1 engine; 0 is an error
df.loc[df['Number.of.Engines'] == 0, 'Number.of.Engines'] = np.nan

# Broad.phase.of.flight: Standardize text formatting
df['Broad.phase.of.flight'] = df['Broad.phase.of.flight'].astype(str).str.strip().str.title()
df['Broad.phase.of.flight'] = df['Broad.phase.of.flight'].replace({'Nan': np.nan})

# Purpose.of.flight: Standardize text formatting
df['Purpose.of.flight'] = df['Purpose.of.flight'].astype(str).str.strip().str.title()
df['Purpose.of.flight'] = df['Purpose.of.flight'].replace({'Nan': np.nan})

In [158]:
for col in ['Weather.Condition', 'Engine.Type', 'Number.of.Engines', 'Broad.phase.of.flight', 'Purpose.of.flight']:
    print(f"=== {col} ===")
    print(df[col].value_counts(dropna=False).head(6))
    print()

=== Weather.Condition ===
Weather.Condition
VMC        58355
IMC         5183
NaN         3262
UNKNOWN      896
Name: count, dtype: int64

=== Engine.Type ===
Engine.Type
Reciprocating    53992
NaN               4621
Turbo Prop        2806
Turbo Fan         2193
Turbo Shaft       2078
Unknown           1455
Name: count, dtype: int64

=== Number.of.Engines ===
Number.of.Engines
1.0    52564
2.0     9492
NaN     4809
3.0      431
4.0      400
Name: count, dtype: int64

=== Broad.phase.of.flight ===
Broad.phase.of.flight
NaN            18126
Landing        12875
Takeoff         9741
Cruise          8348
Maneuvering     6136
Approach        5148
Name: count, dtype: int64

=== Purpose.of.flight ===
Purpose.of.flight
Personal              36301
Instructional          8887
Unknown                5399
NaN                    4828
Aerial Application     3901
Business               3326
Name: count, dtype: int64

### Column Removal
- inspect the dataframe and drop any columns that have too many NaNs

In [159]:
# Drop columns with fewer than 20,000 valid values
df = df.dropna(axis=1, thresh=20000)

# Verify which columns survived the cutoff
print(f"Columns remaining ({df.shape[1]}): {list(df.columns)}")

Columns remaining (33): ['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date', 'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code', 'Airport.Name', 'Injury.Severity', 'Aircraft.damage', 'Aircraft.Category', 'Registration.Number', 'Make', 'Model', 'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'Purpose.of.flight', 'Total.Fatal.Injuries', 'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured', 'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status', 'Publication.Date', 'Total_on_board', 'Severe_Injury_Fraction', 'is_destroyed', 'Make_Model', 'State_Code']

### Save DataFrame to csv
- its generally useful to save data to file/server after its in a sufficiently cleaned or intermediate state
- the data can then be loaded directly in another notebook for further analysis
- this helps keep your notebooks and workflow readable, clean and modularized

In [160]:
# Save clean dataset
df.to_csv('cleaned_aviation_data.csv', index=False)

# Confirm the file was saved with its final row and column dimensions
print(f"Saved successfully. Final dataset shape: {df.shape}")

Saved successfully. Final dataset shape: (67696, 33)